-- Canonical document statuses for formalization flow
ALTER TYPE public.document_status ADD VALUE IF NOT EXISTS 'draft';
ALTER TYPE public.document_status ADD VALUE IF NOT EXISTS 'aprovado';
ALTER TYPE public.document_status ADD VALUE IF NOT EXISTS 'registrado';
ALTER TYPE public.document_status ADD VALUE IF NOT EXISTS 'substituido';
ALTER TYPE public.document_status ADD VALUE IF NOT EXISTS 'cancelado';

-- Persist protocol evidence generated by registry integrations
CREATE TABLE IF NOT EXISTS public.operation_registry_evidences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operation_id UUID NOT NULL REFERENCES public.operations(id) ON DELETE CASCADE,
  document_id UUID REFERENCES public.operation_documents(id) ON DELETE SET NULL,
  provider TEXT NOT NULL,
  protocol TEXT NOT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
  registration_confirmation JSONB,
  idempotency_key TEXT NOT NULL,
  payload_normalized JSONB NOT NULL DEFAULT '{}'::jsonb,
  payload_raw JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_operation_registry_evidences_operation
  ON public.operation_registry_evidences (operation_id);

CREATE INDEX IF NOT EXISTS idx_operation_registry_evidences_document
  ON public.operation_registry_evidences (document_id);

ALTER TABLE public.operation_registry_evidences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own registry evidences"
  ON public.operation_registry_evidences
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.operations op
      WHERE op.id = operation_registry_evidences.operation_id
        AND op.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own registry evidences"
  ON public.operation_registry_evidences
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.operations op
      WHERE op.id = operation_registry_evidences.operation_id
        AND op.user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage registry evidences"
  ON public.operation_registry_evidences
  FOR ALL
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.update_operation_registry_evidences_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_operation_registry_evidences_updated_at ON public.operation_registry_evidences;

CREATE TRIGGER trg_operation_registry_evidences_updated_at
BEFORE UPDATE ON public.operation_registry_evidences
FOR EACH ROW
EXECUTE FUNCTION public.update_operation_registry_evidences_updated_at();
